// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgneawqstfihvtxzoemd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnbmVhd3FzdGZpaHZ0eHpvZW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMjQ4NTAsImV4cCI6MjA3MDgwMDg1MH0.4W807ION2cUfJbx9da77OSGzPR9FHhoRLJWP_2f88xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});